using System;
using System.Linq;
using System.Text;
using SteamPipeStudio.Core.Model;

namespace SteamPipeStudio.Core.Ci;

/// <summary>
/// Emits a GitHub Actions workflow that performs the same upload the GUI does.
///
/// The point is that the desktop app should not become the only way to ship. A build
/// configured by clicking around can be exported to CI verbatim, which is the step
/// most teams eventually need and most GUI uploaders never provide.
///
/// The workflow authenticates with a base64 copy of the steamcmd config produced by a
/// successful interactive login, because Steam Guard cannot be answered by a runner.
/// </summary>
public static class GitHubActionsExporter
{
    public const string ConfigSecretName = "STEAM_CONFIG_VDF";
    public const string AccountSecretName = "STEAM_USERNAME";

    public static string Export(BuildProfile profile, string contentArtifactName = "build")
    {
        var depots = profile.Depots.Where(d => d.Enabled).ToList();
        var branch = string.IsNullOrWhiteSpace(profile.SetLiveBranch) ? "" : profile.SetLiveBranch.Trim();

        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by SteamPipe Studio for {Yaml(profile.Name)} (AppID {profile.AppId}).");
        sb.AppendLine("#");
        sb.AppendLine("# One-time setup:");
        sb.AppendLine("#   1. Sign in once with steamcmd on a machine you control, so that a session");
        sb.AppendLine("#      token is cached. Steam Guard cannot be answered from a CI runner.");
        sb.AppendLine("#   2. base64-encode <steamcmd>/config/config.vdf and store it as the repository");
        sb.AppendLine($"#      secret {ConfigSecretName}.");
        sb.AppendLine($"#   3. Store the builder account name as the secret {AccountSecretName}.");
        sb.AppendLine("#");
        sb.AppendLine("# The token expires. When the workflow starts failing to log in, repeat step 1.");
        sb.AppendLine();
        sb.AppendLine($"name: Deploy to Steam ({Yaml(profile.Name)})");
        sb.AppendLine();
        sb.AppendLine("on:");
        sb.AppendLine("  workflow_dispatch:");
        sb.AppendLine("    inputs:");
        sb.AppendLine("      description:");
        sb.AppendLine("        description: Build description shown in Steamworks");
        sb.AppendLine("        required: false");
        sb.AppendLine($"        default: {Yaml(profile.Description)}");
        sb.AppendLine("      branch:");
        sb.AppendLine("        description: Beta branch to set live (blank uploads without publishing)");
        sb.AppendLine("        required: false");
        sb.AppendLine($"        default: {Yaml(branch)}");
        sb.AppendLine();
        sb.AppendLine("jobs:");
        sb.AppendLine("  deploy:");
        sb.AppendLine("    runs-on: ubuntu-latest");
        sb.AppendLine("    steps:");
        sb.AppendLine("      - uses: actions/checkout@v4");
        sb.AppendLine();
        sb.AppendLine("      # Replace this with however your build is produced or fetched.");
        sb.AppendLine($"      - name: Download build artifact");
        sb.AppendLine("        uses: actions/download-artifact@v4");
        sb.AppendLine("        with:");
        sb.AppendLine($"          name: {Yaml(contentArtifactName)}");
        sb.AppendLine("          path: ./content");
        sb.AppendLine();
        sb.AppendLine("      - name: Install steamcmd");
        sb.AppendLine("        run: |");
        sb.AppendLine("          sudo add-apt-repository -y multiverse");
        sb.AppendLine("          sudo dpkg --add-architecture i386");
        sb.AppendLine("          sudo apt-get update -qq");
        sb.AppendLine("          echo steam steam/question select 'I AGREE' | sudo debconf-set-selections");
        sb.AppendLine("          echo steam steam/license note '' | sudo debconf-set-selections");
        sb.AppendLine("          sudo apt-get install -y steamcmd");
        sb.AppendLine();
        sb.AppendLine("      - name: Restore Steam session");
        sb.AppendLine("        env:");
        sb.AppendLine($"          CONFIG_VDF: ${{{{ secrets.{ConfigSecretName} }}}}");
        sb.AppendLine("        run: |");
        sb.AppendLine("          mkdir -p ~/Steam/config");
        sb.AppendLine("          echo \"$CONFIG_VDF\" | base64 -d > ~/Steam/config/config.vdf");
        sb.AppendLine("          chmod 600 ~/Steam/config/config.vdf");
        sb.AppendLine();
        sb.AppendLine("      - name: Write build scripts");
        sb.AppendLine("        run: |");
        sb.AppendLine("          mkdir -p scripts");
        AppendHeredoc(sb, $"scripts/{Build.BuildScriptGenerator.AppScriptName(profile.AppId)}",
            Vdf.VdfWriter.Write(BuildCiAppNode(profile, depots)));

        foreach (var depot in depots)
            AppendHeredoc(sb, $"scripts/{Build.BuildScriptGenerator.DepotScriptName(depot.DepotId)}",
                Vdf.VdfWriter.Write(Build.BuildScriptGenerator.BuildDepotNode(StripAbsolutePaths(depot))));

        sb.AppendLine();
        sb.AppendLine("      - name: Upload to Steam");
        sb.AppendLine("        env:");
        sb.AppendLine($"          STEAM_USERNAME: ${{{{ secrets.{AccountSecretName} }}}}");
        sb.AppendLine("        run: |");
        sb.AppendLine("          mkdir -p output");
        sb.AppendLine("          steamcmd +login \"$STEAM_USERNAME\" \\");
        sb.AppendLine($"            +run_app_build \"$(pwd)/scripts/{Build.BuildScriptGenerator.AppScriptName(profile.AppId)}\" \\");
        sb.AppendLine("            +quit");
        sb.AppendLine();
        sb.AppendLine("      - name: Publish build logs");
        sb.AppendLine("        if: always()");
        sb.AppendLine("        uses: actions/upload-artifact@v4");
        sb.AppendLine("        with:");
        sb.AppendLine("          name: steampipe-logs");
        sb.AppendLine("          path: output/**/*.log");
        sb.AppendLine("          if-no-files-found: ignore");

        return sb.ToString();
    }

    /// <summary>
    /// The CI checkout has a different layout from the developer's machine, so absolute
    /// paths are rewritten to the workspace-relative ones the workflow creates.
    /// </summary>
    private static Vdf.VdfNode BuildCiAppNode(BuildProfile profile, System.Collections.Generic.List<DepotDefinition> depots)
    {
        var ciProfile = profile.Clone();
        ciProfile.ContentRoot = "./content";
        ciProfile.BuildOutput = "./output";
        ciProfile.LocalContentServerPath = string.Empty;
        return Build.BuildScriptGenerator.BuildAppNode(ciProfile, depots);
    }

    private static DepotDefinition StripAbsolutePaths(DepotDefinition depot)
    {
        var copy = depot.Clone();
        copy.ContentRootOverride = string.Empty;
        return copy;
    }

    private static void AppendHeredoc(StringBuilder sb, string path, string contents)
    {
        sb.AppendLine($"          cat > {path} <<'VDF'");
        foreach (var line in contents.Replace("\r\n", "\n").Split('\n'))
        {
            if (line.Length == 0) continue;
            sb.Append("          ").AppendLine(line);
        }
        sb.AppendLine("          VDF");
    }

    /// <summary>Quotes a scalar so YAML cannot reinterpret it (a bare 1.20 is a float, y is true).</summary>
    private static string Yaml(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
